import SCons

Import('env')

lib_dirs = [d for d in Glob('*') if isinstance(d, SCons.Node.FS.Dir)]
lib_suffix = env['LIBSUFFIX']

for lib in lib_dirs:
	lib_path = lib.get_abspath()
	lib_name = lib.get_path().split('/')[-1]
	src_files = Glob(lib_path+'/src/*.c')

	env['CPPPATH'].append(lib_path+'/header')
	env.Library(lib_name + lib_suffix, src_files)
